### PR TITLE
Build and Push New Training Image that has Scripts Caller

### PR DESCRIPTION
**Pull request by kerrlabajo**
This PR will be responsible for the following implementations:
1. Create a script in yolov5 folder to generalize and call `train.py` or `export.py` with parameters.
2. After executing train and export, move the file according to the parameters destination.
3. Set `build_and_push.sh`` to receive parameters instead of environment variables.

### CODE REVIEW

**Comment by kerrlabajo** [comment]
Updates:
1. All task has been accomplished.
2. There was an attempt to push the image in a Public ECR.
3. However, it is not possible to be used in Visual Studio's `CreateTrainingJobRequest`.
4. Since there will be Role ARN handling, the admin that controls the build and push use case and then retrieves their Private ECR image, policies such as the image URI's accessibility to the admin's employees will be considered but requires further research.

**Review by Ra-Jay — APPROVED** [review]
LGTM

**Comment by kerrlabajo** [comment]
Updates:
1. `train_and_export.py` copies the `best.onnx` in the `/opt/ml/model/` directory and is being handled by SageMaker automatically similar to how `results/` were stored in `/opt/ml/output/data/` directory. This way, it will be stored in the bucket which are both `output.tar.gz` and `model.tar.gz`.
2. Removal of `ExtractAndUploadBestPt` function but use `DownloadObjects` twice for model and output download. This change allows to download both model and output (that has results) as a `.tar.gz` file without any extraction and reuploading the contents.  This was in order to avoid double requests and instead directly downloading the compressed files.
3. As of this update, the current ECR URI tag is version 3.

**Comment by kerrlabajo** [comment]
Updates:
~~Current progress for downloading model and output is taking so long to download which is also difficult to determine if there were any problems from the AWS S3 service or the internet from the user.~~
There were actual internet issue from the user. The download speed was actually fast.

**Pull request merged**
