### PR TITLE
Training Job Logging Feature

### PR DESCRIPTION
**Pull request by kerrlabajo**
This PR will be responsible for the following implementations:
1. Create another background worker for training job request.
2. Display the status of the training job request in the form.
3. Display the log stream of the training job request in the form when the training is in progress.
4. Preferably create another form when performing a new training job request.

In order to open the task list in your Visual Studio, click `Ctrl+\+T` or search `Task List`. Make sure to remove the task that you have implemented/completed.

### CODE REVIEW

**Comment by kerrlabajo** [comment]
image
Please include the training job status logging in the `TrainingInfoForm`.
image
Nevermind, please continue on working this so that it will display in `TrainingInfoForm` and not in console ty.

**Comment by kerrlabajo** [comment]
Add-ons:
Automatically close the `TrainingInfoForm` after the training job has completed.

**Comment by JhonrayAcojedo** [comment]
> image Please include the training job status logging in the `TrainingInfoForm`. image Nevermind, please continue on working this so that it will display in `TrainingInfoForm` and not in console ty.


Yeah temporary pana ang forms

**Comment by JhonrayAcojedo** [comment]
Update: Figured out how to get cloud watch logs, training duration, machine instance type. Then launch new windows forms when pressing training btn. This training duration works for simultaneous training. 

Blocker:
- no expected time end for the training

Additional notes:
- Added new dependency : CloudWatch Logs

TODO: 
- Improve TrainingInfoForms UI
- Add text box for CloudWatch Logs
- Add label for Training Status

**Comment by JhonrayAcojedo** [comment]
Latest commit:
The logs currently does not support simultaneous training. The previous training's logs will stop/not be displayed in the text box.

**Comment by JhonrayAcojedo** [comment]
Current updates:

- Added new dependency : CloudWatch Logs
- Improve TrainingInfoForms UI
- Add text box for CloudWatch Logs
- Add label for Training Status
- Added Cloudwatch logging for training jobs (supports simultaneous training)
- Implemented DeleteDataset function which deletes a custom dataset after training
- UI improvements



Current training form:
formimg


Current Training Info form:
traininginfoimg

**Comment by JhonrayAcojedo** [comment]
Updates: 
- Training button will be now disabled while a training job is ongoing
- Merged Training Job Form to Form1
- Show dialog box in errors
- Clicking the "New Training Job" button will launch a new form

UI Updates:
Before Training is executed:
image

After Training Job is executed:
image

**Comment by kerrlabajo** [comment]
Major update to the UI
Screenshot (416)

**Comment by kerrlabajo** [comment]
Major update to the UI and its functionalities:
1. Set training info details as `Windows.Form.Label`.
2. Disables all forms of user input (i.e. _image size, batch size, select dataset, upload_, etc.,) after the training started. Only enables the user inputs once the training is finished.
3. When mouse hovers to `logBox`, set the mouse as loading/waiting. Set back to normal after the training finishes.
4. Add return points for some repetitive/unending loops especially in the logstream/training job describers. There were repetitive setting of training status and/or in `logBox` that was needed to be stopped.
5. Clear the `logBox` and the training info details from previous training if the user intends to train again in the same `Form1`.
6. Removal of redundancies.
image

**Pull request merged**
