### PR TITLE
Feat/create winforms build tests

### PR DESCRIPTION
**Pull request by JhonrayAcojedo**
This pr is responsible for:

- Further refactoring. Extracted S3 related functions from AWS_Helper into a separate Interface.
- Add Instance Count validation
- Calculating the batch size based on the instance count and instance type. However accurate batch is only available for supported instances. Other instance would default to "-1" for auto batching.
- Trainings resulting in failure will now not delete the dataset.
- Fix double file folder in the CUSTOM_UPLOADS_URI should the user upload the same file twice.
- Put indicators for file upload in the training job information
- UI will now show only the filename instead of the file path of the selected file to upload.

### CODE REVIEW

**Comment by kerrlabajo** [comment]
> Other instance would default to "-1" for auto batching.

Batch size should only be set to `-1` if and only if:
- There are only 1 instance count.
- There are only 1 GPU = (Device is only set to 0).

Otherwise, it won't work. If instance count and/or GPU device > 1, batch size should depend on the instance type's GPU memory, the number of GPU device per instance, and the total number of instances.

**Comment by kerrlabajo** [comment]
Make sure to add a final validation of the batch size even after calculating it when the user starts the training in the application. Pre-emptively assume that "what if the user modifies the batch size" despite it was already calculated when setting the instance count.


Additionally, make sure other training parameters have validations for null/empty cases.

**Comment by JhonrayAcojedo** [comment]
> > Other instance would default to "-1" for auto batching.
> 
> Batch size should only be set to `-1` if and only if:
> - There are only 1 instance count.
> - There are only 1 GPU = (Device is only set to 0).
> 
> Otherwise, it won't work. If instance count and/or GPU device > 1, batch size should depend on the instance type's GPU memory, the number of GPU device per instance, and the total number of instances.

So I have to list every instances that is available for spot training and get their gpu memory? Not just the supported ones?

**Comment by JhonrayAcojedo** [comment]
> Make sure to add a final validation of the batch size even after calculating it when the user starts the training in the application. Pre-emptively assume that "what if the user modifies the batch size" despite it was already calculated when setting the instance count.
> 
> 
> Additionally, make sure other training parameters have validations for null/empty cases.

I did consider this scenario but what if the user really wants to modify the batch size? The field is editable so the user can set their desried batch size. I could put a final validator if the chosen batch size is greater than 0 or something

**Comment by JhonrayAcojedo** [comment]
> Additionally, make sure other training parameters have validations for null/empty cases.


I also considered this and will ask for the default values of the other training parameters should the inputs are null/empty cases

**Comment by kerrlabajo** [comment]
> > > Other instance would default to "-1" for auto batching.
> > 
> > 
> > Batch size should only be set to `-1` if and only if:
> > 
> > * There are only 1 instance count.
> > * There are only 1 GPU = (Device is only set to 0).
> > 
> > Otherwise, it won't work. If instance count and/or GPU device > 1, batch size should depend on the instance type's GPU memory, the number of GPU device per instance, and the total number of instances.
> 
> So I have to list every instances that is available for spot training and get their gpu memory? Not just the supported ones?

1. Just make sure to validate that batch size should not be `-1` for other instances (i.e., >1) outside of the supported ones. 

2. To validate the number of GPU devices, regardless of supported/non-supported instance, batch size should not be `-1` if and only if the `txtDevice.Text` == `0,1,2,3` or `0,1,...N`.

**Comment by kerrlabajo** [comment]
> > Make sure to add a final validation of the batch size even after calculating it when the user starts the training in the application. Pre-emptively assume that "what if the user modifies the batch size" despite it was already calculated when setting the instance count.
> > Additionally, make sure other training parameters have validations for null/empty cases.
> 
> I did consider this scenario but what if the user really wants to modify the batch size? The field is editable so the user can set their desried batch size. I could put a final validator if the chosen batch size is greater than 0 or something

You need to add a final validator that their desired or inputted batch size (if ever modified) is greater than or equal to the calculated batch size, is what I am saying.

**Comment by kerrlabajo** [comment]
> > Additionally, make sure other training parameters have validations for null/empty cases.
> 
> I also considered this and will ask for the default values of the other training parameters should the inputs are null/empty cases

No need to really set different default values, just make sure to capture null/empty cases and that it is not allowed. Other than that, the moment the user opens the application, _the_ default values are already there.

**Comment by kerrlabajo** [comment]
There is a way to refactor your switch-case in validating all training parameters due to its repetitive results. Please find a way to refactor that part. Other than that, the rest is ok.

Tell me if you also have tested and make QA for these cases to ensure it is working. Thanks.

**Comment by JhonrayAcojedo** [comment]
> There is a way to refactor your switch-case in validating all training parameters due to its repetitive results. Please find a way to refactor that part. Other than that, the rest is ok.
> 
> Tell me if you also have tested and make QA for these cases to ensure it is working. Thanks.

Yes i have tested and QA the current validation function. All are working as it should. I will work on refactoring the function in a while.

**Comment by kerrlabajo** [comment]
@JhonrayAcojedo please remove unused variables throughout the project and if possible can you try resolving await operators or maybe make all methods to asynchronous? Just make sure to research which is the best practice or approach for winforms. After that we can merge this branch.

**Review by kerrlabajo — APPROVED** [review]

**Pull request merged**
