### PR TITLE
AWS SageMaker Training Job Creation Implementation

### PR DESCRIPTION
**Pull request by kerrlabajo**
This PR will be responsible in upholding the team's following development:
1. Initialize `Amazon.SageMaker.AmazonSageMakerClient` connection upon running the windows form app.
2. Dataset uploadation in the form of `.rar` or `.zip` file.
3. Receive training parameters from the users.
4. Text area to debug problems for development/production.
5. Implementation of training job creation using a `specific training algorithm for yolov5` in the form of image previously uploaded in **AWS ECR**, defining the **EC2 Instance** (Virtual Machine) that is in free version, and other configurations that was based from the `AWS Training Job Creation` in **AWS Console Management** (Web Interface).

### CODE REVIEW

**Review by kerrlabajo — COMMENTED** [review]
@JhonrayAcojedo tarunga lang nya ang commit message sunod. Abi nako literally nag `Upload zipfile` ka sa akong notifications hahaha.
Bisag keywords lng gud nga "Create button for upload dataset"

**Comment by JhonrayAcojedo** [comment]
mb HAHAHHAA

**Comment by JhonrayAcojedo** [comment]
> @JhonrayAcojedo tarunga lang nya ang commit message sunod. Abi nako literally nag `Upload zipfile` ka sa akong notifications hahaha. Bisag keywords lng gud nga "Create button for upload dataset" and shit

mb HAHAHAHA

**Comment by kerrlabajo** [comment]
@JhonrayAcojedo i-merge lng nya ni nga branch if wala nakay laing ipush related sa sagemaker implementation since ang next to dev kay ang S3 man. Ako ra mo reopen another branch for the 'dev/aws-sagemaker-input-config' after ma merge kani og branch 'dev/aws-s3-implementation'.

**Review by JhonrayAcojedo — APPROVED** [review]
lgtm

**Pull request merged**
